name: Email Notification

on:
  push:
    branches:
      - master

jobs:
  send_email_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Jenkins Job Execution Successful"
          to: admin@example.com
          body: |
            The Jenkins job for containerizing the application and pushing it to Docker Hub has been executed successfully.
